name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          # Deploy the repository root contents to the gh-pages branch
          branch: gh-pages
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}

